### ISSUE TITLE
Video / YouTube embed not working

### ISSUE THREAD

**Issue by paulkre** [montagmorgens/mo-core-functionality#7]
Auf meinem Server funktioniert die Einbettung von YouTube-Videos nicht, weil das Twig-Template an folgender Stelle nicht gefunden wird:

https://github.com/montagmorgens/mo-core-functionality/blob/1baa5a05331186c1823add1cde1d2f2577ddcbe1/lib/Core/Video_Embed.php#L91

Anscheinend wird der Pfad des Templates von Timber nicht als absolut interpretiert. Wenn ich die Zeile folgendermaßen umschreibe, funktioniert es:

```php
\Timber\Timber::$locations = \Mo\Core\PLUGIN_PATH . 'views';
\Timber::render( 'video-embed.twig', $data );
```

**Comment by montagmorgens** [comment]
@paulkre Sorry, ich sehe diese Issue gerade erst – hat sich das Problem ohne Changes am Code auf deinem Server lösen lassen?

**Comment by paulkre** [comment]
Das Problem ist nach der finalen Datenübertragung nicht mehr aufgetreten. Ich weiß allerdings nicht, was die ursprüngliche Ursache war.
